<?php
/**
 * Implements hook_menu_block_blocks().
 */
function slcc_sidebar_menu_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'slcc_sidebar_menu-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => '',
      'level'       => 2,
      'follow'      => '0',
      'depth'       => 0,
      'expanded'    => 0,
      'sort'        => 0,
    ),
  );
}
