<?php

/**
 * @file
 * Module file for slcc_custom_breadcrumbs.
 */

/**
 * Implements hook_views_post_render().
 */
function slcc_custom_breadcrumbs_views_post_render( &$view, &$output, &$cache ) {
  if ( $view->name == 'chapel_sermons' && $view->current_display == 'page' ) {
    if ( !empty($view->build_info['substitutions']) ) {
      $context = $view->build_info['substitutions']['%1'];
    }
    $crumbs = array();
    $crumbs[] = l(t('Home'), '<front>');
    $crumbs[] = l(t('Student Life'), 'student-life');
    if (isset($context)) {
      $crumbs[] = l(t('Chapel Messages'), 'student-life/chapel-messages');
      $crumbs[] = $context;
    } else {
      $crumbs[] = t('Chapel Messages');
    }
    drupal_set_breadcrumb($crumbs);
  }
}
