<?php

/**
 * @file
 * Module file for athletics_schedule_titles.
 */

/**
 * Implements hook_views_pre_view().
 */
function athletic_match_views_pre_view(&$view, &$display_id, &$args) {
  if ( $view->name == 'athletics_calendar' && $display_id == 'page' ) {
    switch ( $args[0] ) {
      case 'mens-basketball':
        $view->display_handler->default_display->options['title'] = "Men's Basketball Schedule";
        break;
      case 'mens-soccer':
        $view->display_handler->default_display->options['title'] = "Men's Soccer Schedule";
        break;
      case 'womens-basketball':
        $view->display_handler->default_display->options['title'] = "Women's Basketball Schedule";
        break;
      case 'womens-volleyball':
        $view->display_handler->default_display->options['title'] = "Women's Volleyball Schedule";
        break;
    }
  }
}
