<?php

/**
 * @file
 * Module file for athletics_schedule_titles.
 */

/**
 * Implements hook_views_post_render().
 */
function athletics_schedule_titles_views_post_render(&$view, &$output, &$cache) {
    // I couldn't figure out a way to add the apostrophe within views ui,
    // so I'm making this module do the work for me.
    if ( $view->name == 'athletics_calendar' && $view->current_display == 'page' ) {
        switch ( $view->build_info['substitutions']['!1'] ) {
            case 'mens-basketball':
                $view->set_title("Men's Basketball Schedule"); break;
            case 'mens-soccer':
                $view->set_title("Men's Soccer Schedule"); break;
            case 'womens-basketball':
                $view->set_title("Women's Basketball Schedule"); break;
            case 'womens-volleyball':
                $view->set_title("Women's Volleyball Schedule"); break;
        }
    }
}
