<?php
/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function my_wysiwyg_configurator_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    // Using ckeditor, set custom config file.
    $settings['customConfig'] = base_path() . drupal_get_path('module', 'my_wysiwyg_configurator') . '/my_wysiwyg_configurator_ckeditor_config.js';
  }
}
